[package]
name = "serde_ternary_fields_macro"
version = "0.1.0"
authors = ["Jon Spalding <jon@cvpartner.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
quote = "1.0.0"
syn = { version = "1.0.3", features = ["full"] }
