[package]
name = "optional-fields-serde-macro"
version = "0.1.0"
authors = ["CV Partner <techsupport@cvpartner.com>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
quote = "1.0.0"
syn = { version = "1.0.3", features = ["full"] }
